services:
  app:
    build: .
    container_name: todo-list-api
    restart: always
    ports:
      - "3333:3333"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: